services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./backend/data:/app/data
