version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Exponemos el puerto 80 al mundo
    depends_on:
      - backend

  backend:
    build: ./backend
    # NO es necesario exponer el puerto 3000 al mundo (ports)
    # porque Nginx le hablará por la red interna de Docker.
    expose:
      - "3000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/src/db:/app/src/db